"""The builder has its own tests. These MAY generate PDFs -- into tmp_path, never
into tests/fixtures/. The committed fixtures are artifacts and are never
regenerated by a test run.
"""

import pdfplumber

from tests.fixtures.build_fixtures import ReportSpec, StatementBlock, build_report


def _tiny_spec() -> ReportSpec:
    return ReportSpec(
        title="Test Industries Limited",
        subtitle="Annual Report 2023-24",
        leading_filler_pages=2,
        trailing_filler_pages=1,
        blocks=(
            StatementBlock(
                heading="Consolidated Balance Sheet",
                caption="(Rs. in crore)",
                header=("Particulars", "FY2024", "FY2023"),
                rows=(
                    ("Total assets", "13,620.00", "12,160.00"),
                    ("Total equity", "6,930.00", "5,980.00"),
                ),
            ),
        ),
    )


def test_build_report_places_blocks_on_predictable_pages(tmp_path):
    out = tmp_path / "tiny.pdf"
    build_report(_tiny_spec(), out)

    with pdfplumber.open(out) as pdf:
        # 1 cover + 2 filler + 1 statement + 1 filler
        assert len(pdf.pages) == 5
        text = pdf.pages[3].extract_text()
        assert "Consolidated Balance Sheet" in text
        assert "(Rs. in crore)" in text


def test_built_tables_are_detectable_by_pdfplumber(tmp_path):
    # Ruled GRID lines are what make the pdfplumber lattice strategy work. If
    # this breaks, every Phase 2 extraction test breaks with it.
    out = tmp_path / "tiny.pdf"
    build_report(_tiny_spec(), out)

    with pdfplumber.open(out) as pdf:
        tables = pdf.pages[3].extract_tables()

    assert len(tables) == 1
    assert tables[0][0] == ["Particulars", "FY2024", "FY2023"]
    assert tables[0][1] == ["Total assets", "13,620.00", "12,160.00"]


def test_generation_is_byte_deterministic(tmp_path):
    first, second = tmp_path / "a.pdf", tmp_path / "b.pdf"
    build_report(_tiny_spec(), first)
    build_report(_tiny_spec(), second)
    assert first.read_bytes() == second.read_bytes()
